# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: bike-share-development
  host: localhost

test:
  adapter: postgresql
  database: bike-share-test
  host: localhost

production:
  adapter: postgresql
  database: postgresql-crystalline-46988

